#ifndef CONTROLLER_STATUS_DEF_H
#define CONTROLLER_STATUS_DEF_H

typedef enum{
  CONTROLLER_ZERO_COUNT = 0,
  CONTROLLER_UNKNOWN_STATUS,
  CONTROLLER_OK,
  CONTROLLER_END_COUNT
} controller_status_t;


#endif